### PR TITLE
Packaging rework

### PR DESCRIPTION
**Pull request by K900**
Please tick as appropriate:
- [x] I have tested this code on a steam deck or on a PC
- [x] My changes generate no new errors/warnings
- [ ] This is a bugfix/hotfix
- [x] This is a new feature

If you're wanting to update a translation or add a new one, please use the weblate page: https://weblate.werwolv.net/projects/decky/

# Description

As promised in #528.

This reworks Decky's packaging to look more like a normal Python package, allowing us to use the package metadata for updates and such. The only part missing right now is actually setting the correct version in CI, which is the most interesting one, but I'm posting this as a draft to hopefully get some feedback.

### CODE REVIEW

**Comment by TrainDoctor** [comment]
Looking good already @K900. We are actually trying a fix for some regressions by downgrading python to 3.10.6. I'll let you know if we go forward with this change (more than likely).

**Comment by K900** [comment]
What kind of regressions? I'd be very surprised if there are actual regressions related to Python versions and not the packaging.

**Comment by TrainDoctor** [comment]
> What kind of regressions? I'd be very surprised if there are actual regressions related to Python versions and not the packaging.

Plugins not working, and Decky itself misbehaving on users devices. We're trying to rule out each potential change and starting with the python backend.

**Comment by K900** [comment]
Also this includes the changes from #528 because this undoes one of those changes.

**Comment by TrainDoctor** [comment]
> Also this includes the changes from #528 because this undoes one of those changes.

Probably safe to close that one then? This looks good already. Myself as leading the CI work and @SkyLeite who develops our CLI tool should both take a look at this so we can provide you the desired feedback.

**Comment by K900** [comment]
I'd rather get #528 merged first as those changes are tiny and this will need a bunch of tweaking and testing before we're confident in it.

**Comment by K900** [comment]
Also ping here: is the general approach something you're interested in? I don't really want to keep rebasing this if it's not going to land.

**Comment by TrainDoctor** [comment]
> Also ping here: is the general approach something you're interested in? I don't really want to keep rebasing this if it's not going to land.

Definitely interested, I'm waiting for @AAGaming00 to approve #528 before I go forward with this PR. Please let us know when you're ready to remove the draft status of this PR.

**Comment by K900** [comment]
I think if I rebase this, it'll be mergeable as-is, and we can then redo the CI bits to make versioning work correctly in a follow-up. Though I haven't really tested the on-device deployment scripts carefully enough, as those don't really work on NixOS anyway.

**Comment by AAGaming00** [comment]
I'm also very much interested in this, will likely merge it once it works in CI

**Comment by K900** [comment]
Rebased on top of master, and realized this isn't actually mergeable as-is, as the tags will be versioned wrong, but I can revert that logic.

**Comment by K900** [comment]
OK, so this should be mergeable now. This is _just_ packaging changes, there's a few tiny behavior changes to make it work with the new packaging, but this should be good to go.

**Comment by K900** [comment]
Note that this doesn't actually embed the version metadata into the archive, that will require reorganizing the CI scripts, but that can be done in a separate change.

**Comment by K900** [comment]
Added another very small fix to make it so the CI artifacts are usable directly, without prior setup on the system.

**Comment by K900** [comment]
Um, anyone?

**Comment by TrainDoctor** [comment]
Apologies, I've been busy with work. Come the start of November I'll take a look at this and do some testing.

**Comment by K900** [comment]
Are you still interested in this? I can rebase, or I can drop this change and keep #528 vendored on our end.

**Comment by TrainDoctor** [comment]
> Are you still interested in this? I can rebase, or I can drop this change and keep #528 vendored on our end.

It will take a lot of refactoring to get this up to snuff. I think ya'll vendoring the adjustments you need in order to distribute for Nix will be the best path. I don't have time to maintain changes that are focused on one or multiple distros (outside of basic compatibility etc). Thanks for making a great PR though. When I first viewed it I was very interested in merging it but time and the codebase have gotten away me in a way that just makes adopting this PR impractical.

**Comment by K900** [comment]
Honestly, pretty much all the changes in this that actually touch the code are automated - it shouldn't take me long to redo them on top of latest master, assuming you're interested.

**Comment by TrainDoctor** [comment]
> Honestly, pretty much all the changes in this that actually touch the code are automated - it shouldn't take me long to redo them on top of latest master, assuming you're interested.

Go ahead and go for that then, I can't promise it will be merged due to ongoing bigger changes to the backend but I would like to get things working smoothly. I will be having @PartyWumpus @marios8543 and @AAGaming00 review this before it gets merged though as they are working on a bunch of stuff with the python backend and I don't want their work to cause future PRs like this to languish again.

**Comment by K900** [comment]
Should I just drop by Discord and talk through the changes with y'all at some point?

**Comment by TrainDoctor** [comment]
> Should I just drop by Discord and talk through the changes with y'all at some point?

That'd be awesome yes!

**Comment by K900** [comment]
Actually, looking at the repo right now, I'm pretty sure most of the code changes I've got here are no longer necessary, so I'll try to redo the packaging changes tomorrow.

**Review by AAGaming00 — CHANGES_REQUESTED** [review]
wtf is this versioning? where does 2.0a come from?????????

**Comment by K900** [comment]
> wtf is this versioning? where does 2.0a1 come from?

This is just a placeholder, the version will be pulled from git when built in CI.

**Comment by K900** [comment]
Updated this. 

The first few commits are small fixes that aren't really related to the big change - I can resubmit them separately if you want. 
- d9f246f6ca607648eeb89ab415123e9e90f38b23 makes it so the frontend JS is always refetched, even if the timestamps on the files are invalidated by the package manager, clock skew or any other reason
- fca985fc0e0f05e4a290445d3108378c92e73516 cleans up the act/ shell script to pass shellcheck
- 4eac938e5ab2ca935f4366bd0c6101ff627639ae makes it harder to accidentally commit the settings directory when running the backend from in-tree
- 6ebf845245701feec10f888d1a268fa36c4510d5 makes the backend not complain about missing directories when running out of a clean tree

7644e93f6b842312571ff4f38868dd9193adced8 contains the bulk of the changes, now a lot less invasive. The `src` to `decky_loader` move isn't strictly necessary, but makes things easier for both poetry and pyinstaller.

This doesn't actually change how the versions are looked up yet, because it does require somewhat invasive reordering of CI steps, I can either add it here or send a follow-up after.

**Comment by marios8543** [comment]
I like it. Refactoring the backend folder so it follows the structure of a python project more is definitely the right call. A few notes, `decky_plugin.py`, in its current form needs to have its path added as a python path so plugins can find and import it, and also have its path in the pyinstaller data add. Also some refactoring changes have been made already by AA and me, check out [my branch](https://github.com/SteamDeckHomebrew/decky-loader/tree/marios8543/async-plugin-method-requests/backend/src), and there will be a few more changes with language-independent backends, coming a bit further down the road. You can dismiss the `src` subdir in favor of the more pythonic form you have, but if you could rebase based on my branch it would be great.

Good work at any rate!

**Comment by K900** [comment]
`decky_plugin` would end up on PYTHONPATH by default because I'm adding it to Pyinstaller's `hidden_imports`, so it gets copied into the final site-packages. I'll rebase in a bit.

**Comment by K900** [comment]
Rebased, had to pick up the changes from master, otherwise there's a merge conflict between yours and cc0841260320f59870e513c559f9dab1103e6437

**Comment by marios8543** [comment]
Uh you probably need to change `src.` **[here](https://github.com/K900/decky-loader/blob/fedfb3f7330f3289107c8d4ad10a1acc61c1a6bb/backend/decky_loader/plugin/sandboxed_plugin.py#L77)** to `plugin_loader.` or something, so plugins can import the modules. Eg steamgriddb fails with:
`
[sandboxed_plugin][ERROR]: Failed to start SteamGridDB!
Traceback (most recent call last):
   File "decky_loader/plugin/sandboxed_plugin.py", line 85, in initialize
   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
   File "/home/deck/homebrew/plugins/decky-steamgriddb/main.py", line 11, in <module>
     from settings import SettingsManager # type: ignore
 ModuleNotFoundError: No module named 'settings'
` which is consistent to how it failed when we refactored to src. before

**Comment by K900** [comment]
Oh, uh, yes, that is very cursed.

**Comment by marios8543** [comment]
We're gonna refactor what modules plugins can access eventually, to a common stable API that's independent to decky internals, but for now we should keep it compatible with existing plugins.

**Comment by K900** [comment]
Applied.

**Comment by marios8543** [comment]
```
 [sandboxed_plugin][ERROR]: Failed to start SteamGridDB!
 Traceback (most recent call last):
   File "decky_loader/plugin/sandboxed_plugin.py", line 79, in initialize
 KeyError: 'localplatform.localplatformlinux'
```
fails like this now. Not sure if anything else changed structure-wise

**Comment by K900** [comment]
I think this one should work.

**Comment by marios8543** [comment]
Yep this works great.

**Comment by marios8543** [comment]
Oh you set my async request branch as base. I think I can go ahead and merge it then

**Pull request merged**
