### PR TITLE
Updater for decky-loader

### PR DESCRIPTION
**Pull request by AAGaming00**
Adds the ability for decky-loader to update itself via an option in settings, also displaying the current and latest availiable pre-release version. Easily updatable in the future to include a branch select.

This also updates all installed NPM packages in frontend, and edits tsconfig to allow React Fragments to work.

### CODE REVIEW

**Comment by botatooo** [comment]
I assume decky-frontend-lib has also been updated to use the progress bars?

**Comment by TrainDoctor** [comment]
> I assume decky-frontend-lib has also been updated to use the progress bars?

It was updated pre-emptively by @AAGaming00.

**Comment by AAGaming00** [comment]
> I assume decky-frontend-lib has also been updated to use the progress bars?

Yes.

**Comment by AAGaming00** [comment]
[Video](https://cloud.aa.catvibers.me/s/9NDXcjj9WgNDrHL)

**Comment by botatooo** [comment]
For the plugin url install button, instead of checking the length could we check if the url is valid instead? (e.g. `new URL(pluginURL)` errors if it's given an invalid url)

**Pull request merged**
