### PR TITLE
Testing PRs from within decky

### PR DESCRIPTION
**Pull request by PartyWumpus**
Please tick as appropriate:
- [x] I have tested this code on a steam deck or on a PC
- [x] My changes generate no new errors/warnings
- [ ] This is a bugfix/hotfix
- [x] This is a new feature

# Description

Adds a testing menu (which is only visible with developer mode on) to decky's options which lists open PRs and allows you to download them. The info button takes you to the PR's github page. 

Changes needed before merging:
- [x] Run the linter on it
- [x] Disable the decky update stuff when on a testing version
- [x] Make a web backend to download the PRs from ~~(this is the 'help needed' bit)~~

~~The list of PRs could set up in a similar way to the testing store in decky-plugin-database. The `download_testing_version` & `get_testing_versions` functions from updater.py need to be changed to get data from here.~~ The PR list is downloaded via github's API, and the artifacts are downloaded with nightly.link.

image

### CODE REVIEW

**Comment by RodoMa92** [comment]
This is really useful as a feature, great work! I'll try to give you a hand shortly if I have time, but maybe other team members have more time to do this.

**Comment by nabel0** [comment]
What about this PR? Looks realy realy usefull? Will this be merged eventually?
For me as a tester who tests something almost daily and contributes to the cummunity this PR would be very very helpful.

**Comment by PartyWumpus** [comment]
> it should be flagged as draft until all the pieces are in.

Woops, I thought this already was marked as a draft.

**Comment by RodoMa92** [comment]
> > it should be flagged as draft until all the pieces are in.
> 
> Woops, I thought this already was marked as a draft.

NP, just as an heads up for people that want this feature in (including me :P).

**Comment by RodoMa92** [comment]
Everything should be ready, we just need an API to convert the resolved artifact download link back to a downloadable link as a anonymous user (since it seems that Github doesn't allow that for whatever reason).

**Comment by WerWolv** [comment]
I use https://nightly.link/ for exactly this on a few other projects. Doesn't have 100% uptime but it generally works pretty well

**Comment by RodoMa92** [comment]
> I use https://nightly.link/ for exactly this on a few other projects. Doesn't have 100% uptime but it generally works pretty well

Yeah, @AAGaming00 also proposed that. I've tried to paste the resolved artifacts link, but it can't find them. I guess it needs additional permissions from the repo itself to access them, but I would probably prefer that someone else take a look at that before messing up stuff by myself :P

**Comment by AAGaming00** [comment]
Unsure your thoughts on this, but I prefer this be rebased onto aa/websockets as it contains a new (and saner) api for backend<-->frontend rpc and would be likely easier to implement there (and so i dont need to reimplement it on that branch eventually)

**Comment by PartyWumpus** [comment]
> Unsure your thoughts on this, but I prefer this be rebased onto aa/websockets as it contains a new (and saner) api for backend<-->frontend rpc and would be likely easier to implement there (and so i dont need to reimplement it on that branch eventually)

Took a quick look at the websocket branch and if i'm reading it right, it'll make it easier to pass errors up to the JS from the python sanely (was just trying to figure out how to pass errors up in a not stupid way). I assume other benefits too, I haven't read all of it yet.

I would be happy rebasing it, but it would probably delay this further into the future because it has to wait for websockets to be finished. (Not a huge issue because it's already been like 8 months, what's a couple more :p)

**Comment by RodoMa92** [comment]
Switching to ready for testing since I don't see what's still missing as of today. LMK if I've missed something.

**Comment by AAGaming00** [comment]
We should probably contact the nightly.link people and ask if they're okay with this or if they would prefer us to run our own service.

**Comment by RodoMa92** [comment]
> We should probably contact the nightly.link people and ask if they're okay with this or if they would prefer us to run our own service.

Ok, feel free to do that if you can :)

**Comment by RodoMa92** [comment]
Another thing to add is a motd like on CSSLoader to warn the user that these are unvetted builds and to use them on their own risk etc.

I took a look at that component in CSSLoader and assuming that they are fine with this I would like to port that into a Decky component to be used for us (it might be useful to warn people on potential breakages etc like on CSSLoader) even on other parts of the Decky UI.

**Comment by beebls** [comment]
> Another thing to add is a motd like on CSSLoader to warn the user that these are unvetted builds and to use them on their own risk etc.
> 
> I took a look at that component in CSSLoader and assuming that they are fine with this I would like to port that into a Decky component to be used for us (it might be useful to warn people on potential breakages etc like on CSSLoader) even on other parts of the Decky UI.

Our MOTD component in CSSLoader is designed to fetch a current MOTD from the server and display that.

This seems like it would be better served with a static, hardcoded message.

Whatever you wish to use it for, our code is GPL3 and you're free to repurpose it :), if you do have any questions you can reach me on discord, I don't get Github notifications on my phone.

**Comment by PartyWumpus** [comment]
> Another thing to add is a motd like on CSSLoader to warn the user that these are unvetted builds and to use them on their own risk etc.

Probably best to copy the one [the testing store](https://github.com/SteamDeckHomebrew/decky-loader/blob/3e4c255c5bbf70923e9b2fd831eef22d2b037dc1/frontend/src/components/store/Store.tsx#L185:L214)

**Comment by RodoMa92** [comment]
> > Another thing to add is a motd like on CSSLoader to warn the user that these are unvetted builds and to use them on their own risk etc.
> 
> Probably best to copy the one in [the testing store](https://github.com/SteamDeckHomebrew/decky-loader/blob/3e4c255c5bbf70923e9b2fd831eef22d2b037dc1/frontend/src/components/store/Store.tsx#L185:L214)

Fair, I was mainly referring to the style. Having that component might be useful to avoid repeated questions in the server on the same thing tho. Might open a separate PR for that.

**Comment by PartyWumpus** [comment]
> Unsure your thoughts on this, but I prefer this be rebased onto aa/websockets as it contains a new (and saner) api for backend<-->frontend rpc and would be likely easier to implement there (and so i dont need to reimplement it on that branch eventually)

@AAGaming00, because this feature is functionally done now, i think it would make more sense to just merge this as is, and make a new PR for aa/websockets. (although i'm not totally certain what the best way to do that is. just merge main into websockets and fix from there?)

**Comment by PartyWumpus** [comment]
That makes sense, but I meant I'd be doing the merging, not you.

**Comment by AAGaming00** [comment]
Sure, feel free to port it over to websocket yourself once websocket is ready to be merged to main. (and by "merged to main" I mean another branch created matching the final state of main, and then main is reset to websocket)

**Comment by TrainDoctor** [comment]
Marking this as backlog until such time as we can reintroduce it.

**Review by TrainDoctor — APPROVED** [review]
Approved, going to push this forward as it will be a net benefit for testing new Decky features.

**Pull request merged**
