### PR TITLE
Add cross-platform support to decky

### PR DESCRIPTION
**Pull request by suchmememanyskill**
This PR overhauls decky's backend code to make it cross compatible on windows. Notable changes include:
- Removing all inline cli calls to chown/chmod/systemctl in favor of wrappers managed by the `localplatform.py` file.
    - Chown now does not accept specific user id's anymore, but rather an abstraction in the form of `UserType.HOST_USER`, `UserType.EFFECTIVE_USER` and `UserType.ROOT`.
- Rewrite the logic of sockets for `plugin.py` so that multiple socket types are supported.
    - Note: This also seperates all socket logic into `socket.py`, making `plugin.py` just focused on loading an managing plugins.
- The action workflow has been edited to automatically build a windows binary.
- `updater.py` now downloads the new PluginLoader binary first, then moves it to the right place. This was required for windows to work (you cannot modify a running executable in windows).
- From the https://github.com/SteamDeckHomebrew/decky-loader/pull/353 PR,
    - Imports were moved to main.py, so they don't run multiple times.
    - `get_system_pythonpaths()` has been overhauled to use newlines for splitting paths and to add a failsafe.
    
    
This PR messes with a lot of the core functionality of decky. I have tested everything in this PR, on both windows and steamos and everything *appears* to run fine. Requesting your re-evaluation to double check my work. Please also review the changed code to make sure i didn't do anything weird. I'm sure this PR is nowhere near final yet, but i'd love to hear your feedback.

**For normal users, please do not ask for how to run this.**

Issues to work out still:
- Websockets are abysmally slow on windows. A workaround may be needed for this

### CODE REVIEW

**Review by TrainDoctor — APPROVED** [review]
Current cursory testing seems to indicate working as intended. I'll test this PR for the rest of the weekend and if I and others don't encounter any issues then this will likely be merged late sunday. Thanks for the great work @suchmememanyskill.

**Comment by doZennn** [comment]
I would like to propose a new field in plugin.json to specify the supported platforms and for the store to filter unsupported plugins out based on that.

**Comment by TrainDoctor** [comment]
> I would like to propose a new field in plugin.json to specify the supported platforms and for the store to filter unsupported plugins out based on that. And possibly for the loader to not attempt to load a plugin unless it's the correct platform as a safety net.
> 
> ~This is probably the wrong place for this but i figured it would be okay here since i couldn't find a main place to discuss multiplat stuff~

This is a good idea but I don't think we have plans to support decky for windows via any time soon. Please make this suggestion again when we start making a minor features suggestion project for plugin api v2.

**Comment by TrainDoctor** [comment]
No objections to this have been raised, merging into decky.

**Pull request merged**
