### PR TITLE
Add Plugin Reload Button to Settings

### PR DESCRIPTION
**Pull request by Scrumplex**
Moves plugin actions into context menu, adds Reload action

Screenshot plugin list
Screenshot context menu

### CODE REVIEW

**Comment by Scrumplex** [comment]
I think using buttons here is not the right way, as you need to navigate up/down to select buttons that are next to each other (in the same row)

**Review by AAGaming00 — APPROVED** [review]
LGTM

**Review by TrainDoctor — CHANGES_REQUESTED** [review]
Needs to be rebased to latest main. Currently tries to grab new updates using the old version finding function.

**Review by TrainDoctor — APPROVED** [review]
Rebase to latest main addressed issues with updater grabbing placeholder for older decky clients.
Merging.
Thanks for your contribution!

**Pull request merged**
