### PR TITLE
File picker improvments

### PR DESCRIPTION
**Pull request by doZennn**

### CODE REVIEW

**Comment by TrainDoctor** [comment]
Requesting response from developer as to whether this PR will continue and be prepared to merge or if it should be closed. Thanks.

**Comment by doZennn** [comment]
This is still alive.

**Comment by doZennn** [comment]
Won't unfortunately, if anyone wants to merge my changes from the SGDB plugin be my guest.

**Comment by Witherking25** [comment]
I can give it a go @doZennn, in a bit doing calc 1 homework

**Comment by doZennn** [comment]
> I can give it a go @doZennn, in a bit doing calc 1 homework

Sweet, thanks. I would suggest not using anything from this PR, I've made some changes in the plugin since.

**Comment by RodoMa92** [comment]
I can take it if you want, at least I can integrate translation directly in the code.

**Pull request closed without merging**
