### PR TITLE
Add CEF Remote Debugging toggle

### PR DESCRIPTION
**Pull request by Scrumplex**
Alternative approach to #61 

This disables the `steam-web-debug-portforward.service` unit on startup, while offering a toggle in the UI which enables and starts the service.

I am personally not quite sure if enabling/disabling is the right approach, as that would be persistent, even if decky would be uninstalled. So maybe we can just start/stop it instead? Feel free to leave your thoughts here.

Screenshot

### CODE REVIEW

**Comment by TrainDoctor** [comment]
Looks good. I'll submit a review once I've been able to test this and I'll have our testers try it out as well. Once the testers have gotten back to us is when we can decide to merge. Thanks for the PR.

**Review by AAGaming00 — CHANGES_REQUESTED** [review]
I have concerns that this will make development of the loader harder. It would be ideal in my opinion if you disabled the port forward only if running from a compiled binary, not when running from source.

**Comment by botatooo** [comment]
Is there a way to check?

**Review by AAGaming00 — APPROVED** [review]
We'd like to get this merged ASAP, but I would like atleast a file that can be created in the homebrew directory to prevent this from auto-applying for developers.

**Review by TrainDoctor — APPROVED** [review]
Looking good, currently dealing with some breaking changes because of an update to webpack on the deck. We'll move to merge this once we've fixed that all up.
Thanks for your contribution!

**Pull request merged**
