### PR TITLE
Use environment variables instead of hard coding home directory

### PR DESCRIPTION
**Pull request by pastaq**
Enables use on other Linux distributions utilizing the gamepadui, such as ChimeraOS.

### CODE REVIEW

**Comment by pastaq** [comment]
Upon further review there are additional instances that need addressing. Marking as WIP until I have completed full review of the codebase.

**Comment by pastaq** [comment]
Fully tested and able to load a test app, as well as navigate to the app store and start installs on ChimeraOS.

**Review by TrainDoctor — APPROVED** [review]
This is really good python. Upon review I see no reason not to merge this ASAP.
Thanks for your contribution!

**Comment by AAGaming00** [comment]
@pastaq if you'd like to update this for the new loader rewrite now merged into main, we can get this merged. Thanks for the contribution!

**Pull request closed without merging**
