### PR TITLE
Turn command id into global

### PR DESCRIPTION
**Pull request by Jan200101**
Please tick as appropriate:
- [x] I have tested this code on a steam deck or on a PC
- [x] My changes generate no new errors/warnings
- [x] This is a bugfix/hotfix
- [ ] This is a new feature

If you're wanting to update a translation or add a new one, please use the weblate page: https://weblate.werwolv.net/projects/decky/

# Description

the response id is tied to the request id thus multiple instances of the Tab class can cause problems when prior messages are not consumed properly

### CODE REVIEW

**Comment by AAGaming00** [comment]
or do they just echo whatever ID we use, that would be fine then

**Comment by Jan200101** [comment]
the format is similar to jsonrpc, the ID I send is the same I receive
This is used to unique identify request and response pairs.

When dealing with multiple different Tab instances this isn't an issue, but when there are multiple Tabs pointing towards the same websocket the same ID is likely to appear since we don't always consume the stream.

**Comment by Jan200101** [comment]
ignore what I said, the format *is* JSON-RPC 1.0

And with that we should set the ID to None when no response is required to inform the server we don't expect a response

**Comment by Jan200101** [comment]
scratch that, they don't support notifications, only requests.

**Comment by TrainDoctor** [comment]
User acting in bad faith. Closed.

**Pull request closed without merging**
