### PR TITLE
Use python executable directly instead of guessing

### PR DESCRIPTION
**Pull request by Jan200101**
In the very unlikely case that no executable was found this will fall back onto "python"

Please tick as appropriate:
- [ ] I have tested this code on a steam deck or on a PC
- [x] My changes generate no new errors/warnings
- [x] This is a bugfix/hotfix
- [ ] This is a new feature

If you're wanting to update a translation or add a new one, please use the weblate page: https://weblate.werwolv.net/projects/decky/

# Description

Instead of blindly guessing the executable just use the currently interpreter executable with a fallback to plain "python"

### CODE REVIEW

**Comment by AAGaming00** [comment]
i think this would break with pyinstaller builds?

**Comment by Jan200101** [comment]
Yep, it would.
Looking further there appears to be no way around this.
Simply looking for "python" is still a bad way of doing this though.

**Comment by HighSpeed1380** [comment]
I want to know the reason why built using python

**Comment by mantikafasi** [comment]
"High Speed" would rather have electron installer

**Comment by marios8543** [comment]
🤮

**Comment by TrainDoctor** [comment]
> "High Speed" would rather have electron installer

We will never use electron for a goddamn installer... No. Just no.

**Pull request closed without merging**
