### PR TITLE
Updated store CSS

### PR DESCRIPTION
**Pull request by GoDev87**

### CODE REVIEW

**Comment by TrainDoctor** [comment]
@GoDev87 could you provide some before and after screenshots for reference? Thanks.

**Comment by GoDev87** [comment]
I have class right now, I'll do that in ~8h.

**Comment by GoDev87** [comment]
image
@TrainDoctor

**Comment by GoDev87** [comment]
image
And this is without any css plugins

**Review by EMERALD0874 — COMMENTED** [review]
This will only be briefly helpful as the whole store will be redesigned in #280 and deviate from the current structure. I'm not sure if it's worth merging these changes.

**Comment by TrainDoctor** [comment]
> This will only be briefly helpful as the whole store will be redesigned in #280 and deviate from the current structure. I'm not sure if it's worth merging these changes.

A decent point but it won't hurt to merge it as a qol measure when we make the next stable release. Merging to main.

**Pull request merged**
