### PR TITLE
CI revamp

### PR DESCRIPTION
**Pull request by botatooo**
### Added:
- Option to run manually (for full-fledged releases)
- Cron schedule for prereleases (every day at 1 pm UTC)
- Semantic versioning (for both releases and prereleases)
- Automatically generated release description

### CODE REVIEW

**Review by AAGaming00 — APPROVED** [review]
LGTM, would like to see this run on your fork to make sure it works.

**Comment by TrainDoctor** [comment]
> LGTM, would like to see this run on your fork to make sure it works.

The builder package is private and as such doesn't run properly on personal forks.

**Comment by AAGaming00** [comment]
> > LGTM, would like to see this run on your fork to make sure it works.
> 
> The builder package is private and as such doesn't run properly on personal forks.

The package isn't private, GHCR just requires any repo's authentication to pull any image from an Action for some reason.

**Comment by AAGaming00** [comment]
Actually, this doesn't even use the builder.

**Pull request merged**
