### PR TITLE
[Feature] Freeze updates for devs

### PR DESCRIPTION
**Pull request by FineWolf**
Please tick as appropriate:
- [x] I have tested this code on a steam deck or on a PC
- [X] My changes generate no new errors/warnings
- [ ] This is a bugfix/hotfix
- [X] This is a new feature

If you're wanting to update a translation or add a new one, please use the weblate page: https://weblate.werwolv.net/projects/decky/

# Description

Allows Developers (when Developer mode is available) to freeze updates for a specific plugin. When frozen, updates will no longer be checked for that plugin. See https://discord.com/channels/960281551428522045/960284311444131840/1201162635224301680 for suggestion.

### CODE REVIEW

**Comment by AAGaming00** [comment]
we should maybe consider prompting to unlock updates for all plugins when disabling developer mode

**Comment by FineWolf** [comment]
> we should maybe consider prompting to unlock updates for all plugins when disabling developer mode

We don't reset any developer oriented setting right now (like `cef_forward`) when developer mode is turned off. This could be done in a separate PR if it is desired.

**Comment by FineWolf** [comment]
Anything I can do to make this PR move forward?

**Comment by TrainDoctor** [comment]
> Anything I can do to make this PR move forward?

Not much you can do, apologies. Hopefully one of our @SteamDeckHomebrew/decky-testers can test this PR.

**Comment by TrainDoctor** [comment]
Was able to test this just now. Works like a charm, merging to add to latest pre-release.

**Review by TrainDoctor — APPROVED** [review]

**Pull request merged**
