### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by WerWolvTranslationBot**
Translations update from [Weblate](https://weblate.werwolv.net) for [Decky/Decky](https://weblate.werwolv.net/projects/decky/decky/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by pvsfair** [comment]
I've added translations to Portuguese Brazillian on the [Weblate Website](https://weblate.werwolv.net/projects/decky/decky/pt_BR/).

**Comment by pvsfair** [comment]
The last 3 translations added (ko-KR, pt-BR, pt-PT) are empty here on this PR. Is this right?

**Comment by RodoMa92** [comment]
> The last 3 translations added (ko-KR, pt-BR, pt-PT) are empty here on this PR. Is it right?

Yeah, weblate hadn't pushed the commits yet, for some reason. They are present now, if you want to check now.

**Comment by OctopusET** [comment]
I have just finished the Korean translation. I checked it three times, I won't make any more changes until other people find errors.

**Comment by OctopusET** [comment]
FYI: My last change had not yet been applied in this PR.

**Pull request merged**
